on:
    workflow_dispatch:
        inputs:
            useMasterIA:
                description: Use the latest master commit of the `internetarchive` Python package (jjjake/internetarchive)
                required: false
                type: boolean

jobs:
    update:
        name: Update archives from the Internet Archive
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Install `internetarchive` from pip
                run: pip install --upgrade ${{ inputs.useMasterIA && "git+https://github.com/jjjake/internetarchive.git" || "internetarchive" }}
            -   name: Download archives
                working-directory: archive
                run: ia download -i --search="uploader:chlod@chlod.net (subject:bulletin)" --glob="*.pdf"
            -   name: Commit new archives
                uses: EndBug/add-and-commit@v9
                with:
                    default_author: github_actions
                    add: "."
                    message: Updating archives
                    push: true
